// AUTO-GENERATED by scripts/brain-graph.mjs — snapshot of the current brain (privacy-safe).
// Do not hand-edit. Re-run: node scripts/brain-graph.mjs
window.__BRAIN__ = {
  "meta": {
    "snapshot": true,
    "note": "every file under memory/ is a node. structure is real. identities and opsec-named files are masked, never named. contents are never shown.",
    "counts": {
      "nodes": 331,
      "links": 336,
      "memoryFiles": 281,
      "totalMemoryFiles": 282
    }
  },
  "families": {
    "core": {
      "label": "core",
      "color": "#d4b872"
    },
    "personality": {
      "label": "personality stack",
      "color": "#8878a8"
    },
    "memory": {
      "label": "memory infra",
      "color": "#a78bfa"
    },
    "people": {
      "label": "people (masked)",
      "color": "#d97a8e"
    },
    "projects": {
      "label": "projects (masked)",
      "color": "#5a8ab5"
    },
    "community": {
      "label": "community (masked)",
      "color": "#27a3b5"
    },
    "workmem": {
      "label": "memos & archive (masked)",
      "color": "#6a6e78"
    },
    "senses": {
      "label": "senses & hands",
      "color": "#93a6bd"
    },
    "systems": {
      "label": "systems & products",
      "color": "#c4a862"
    }
  },
  "nodes": [
    {
      "id": "claude",
      "label": "CLAUDE.md",
      "family": "core",
      "hub": true,
      "note": "operating instructions. the index every session loads first.",
      "degree": 12
    },
    {
      "id": "p-spec",
      "label": "SIBYL-SPEC.md",
      "family": "personality",
      "degree": 1
    },
    {
      "id": "p-voice",
      "label": "SIBYL-VOICE.md",
      "family": "personality",
      "degree": 2
    },
    {
      "id": "p-soul",
      "label": "SIBYL-SOUL.md",
      "family": "personality",
      "degree": 1
    },
    {
      "id": "p-talos",
      "label": "TALOS-PERSONA.md",
      "family": "personality",
      "degree": 1
    },
    {
      "id": "p-erc",
      "label": "ERC8004-PLAN.md",
      "family": "personality",
      "degree": 1
    },
    {
      "id": "p-sys",
      "label": "SIBYL-SYSTEM-PROMPT.md",
      "family": "personality",
      "degree": 1
    },
    {
      "id": "p-gloss",
      "label": "GLOSSARY.md",
      "family": "personality",
      "degree": 1
    },
    {
      "id": "p-diary",
      "label": "SIBYL-DIARY",
      "family": "personality",
      "degree": 1
    },
    {
      "id": "index",
      "label": "INDEX.json",
      "family": "memory",
      "hub": true,
      "note": "memory index. points at every tier.",
      "degree": 20
    },
    {
      "id": "f0001",
      "label": "ARCHIVE01",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0002",
      "label": "ARCHIVE02",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0003",
      "label": "ARCHIVE03",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0004",
      "label": "ARCHIVE04",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0005",
      "label": "ARCHIVE05",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0006",
      "label": "ARCHIVE06",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0007",
      "label": "ARCHIVE07",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0008",
      "label": "ARCHIVE08",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0009",
      "label": "ARCHIVE09",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0010",
      "label": "ARCHIVE10",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0011",
      "label": "ARCHIVE11",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0012",
      "label": "ARCHIVE12",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0013",
      "label": "ARCHIVE13",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0014",
      "label": "ARCHIVE14",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0015",
      "label": "ARCHIVE15",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0016",
      "label": "ARCHIVE16",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0017",
      "label": "ARCHIVE17",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0018",
      "label": "ARCHIVE18",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0019",
      "label": "ARCHIVE19",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0020",
      "label": "ARCHIVE20",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0021",
      "label": "ARCHIVE21",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0022",
      "label": "ARCHIVE22",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0023",
      "label": "ARCHIVE23",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0024",
      "label": "ARCHIVE24",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0025",
      "label": "ARCHIVE25",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0026",
      "label": "ARCHIVE26",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0027",
      "label": "ARCHIVE27",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0028",
      "label": "ARCHIVE28",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0029",
      "label": "ARCHIVE29",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0030",
      "label": "ARCHIVE30",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0031",
      "label": "ARCHIVE31",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0032",
      "label": "ARCHIVE32",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0033",
      "label": "ARCHIVE33",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0034",
      "label": "ARCHIVE34",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0035",
      "label": "ARCHIVE35",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0036",
      "label": "ARCHIVE36",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0037",
      "label": "ARCHIVE37",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0038",
      "label": "ARCHIVE38",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0039",
      "label": "ARCHIVE39",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0040",
      "label": "ARCHIVE40",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0041",
      "label": "ARCHIVE41",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0042",
      "label": "ARCHIVE42",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0043",
      "label": "ARCHIVE43",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0044",
      "label": "ARCHIVE44",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0045",
      "label": "ARCHIVE45",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0046",
      "label": "ARCHIVE46",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0047",
      "label": "ARCHIVE47",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0048",
      "label": "ARCHIVE48",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0049",
      "label": "ARCHIVE49",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0050",
      "label": "ARCHIVE50",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0051",
      "label": "ARCHIVE51",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0052",
      "label": "ARCHIVE52",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0053",
      "label": "ARCHIVE53",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0054",
      "label": "ARCHIVE54",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0055",
      "label": "ARCHIVE55",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0056",
      "label": "ARCHIVE56",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0057",
      "label": "ARCHIVE57",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0058",
      "label": "ARCHIVE58",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0059",
      "label": "ARCHIVE59",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0060",
      "label": "ARCHIVE60",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0061",
      "label": "ARCHIVE61",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0062",
      "label": "ARCHIVE62",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0063",
      "label": "ARCHIVE63",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0064",
      "label": "ARCHIVE64",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0065",
      "label": "ARCHIVE65",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0066",
      "label": "ARCHIVE66",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0067",
      "label": "ARCHIVE67",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0068",
      "label": "ARCHIVE68",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0069",
      "label": "ARCHIVE69",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0070",
      "label": "ARCHIVE70",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0071",
      "label": "base-health.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0072",
      "label": "OPS01",
      "family": "memory",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0073",
      "label": "known-tokens.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0074",
      "label": "OPS02",
      "family": "memory",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0075",
      "label": "OPS03",
      "family": "memory",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0076",
      "label": "endpoint_review_email.txt",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0077",
      "label": "ENDPOINT01",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0078",
      "label": "ENDPOINT02",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0079",
      "label": "ENDPOINT03",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0080",
      "label": "ENDPOINT04",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0081",
      "label": "ENDPOINT05",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0082",
      "label": "ENDPOINT06",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0083",
      "label": "ENDPOINT07",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0084",
      "label": "ENDPOINT08",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0085",
      "label": "ENDPOINT09",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0086",
      "label": "ENDPOINT10",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0087",
      "label": "ENDPOINT11",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0088",
      "label": "_index.json",
      "family": "community",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0089",
      "label": "MEMBER01",
      "family": "community",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0090",
      "label": "MEMBER02",
      "family": "community",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0091",
      "label": "MEMBER03",
      "family": "community",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0092",
      "label": "MEMBER04",
      "family": "community",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0093",
      "label": "MEMBER05",
      "family": "community",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0094",
      "label": "MEMBER06",
      "family": "community",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0095",
      "label": "MEMBER07",
      "family": "community",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0096",
      "label": "USER01",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0097",
      "label": "USER02",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0098",
      "label": "USER03",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0099",
      "label": "USER04",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0100",
      "label": "USER05",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0101",
      "label": "USER06",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0102",
      "label": "USER07",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0103",
      "label": "USER08",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0104",
      "label": "USER09",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0105",
      "label": "USER10",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0106",
      "label": "USER11",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0107",
      "label": "USER12",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0108",
      "label": "USER13",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0109",
      "label": "USER14",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0110",
      "label": "USER15",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0111",
      "label": "USER16",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0112",
      "label": "USER17",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0113",
      "label": "USER18",
      "family": "people",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0114",
      "label": "acp-v2.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0115",
      "label": "advisory-dashboard.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0116",
      "label": "auspex.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0117",
      "label": "PRODUCT01",
      "family": "systems",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0118",
      "label": "discord.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0119",
      "label": "PRODUCT02",
      "family": "systems",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0120",
      "label": "framework-skill.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0121",
      "label": "memory-skill.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0122",
      "label": "ping.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0123",
      "label": "sibyl-memory-demo.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0124",
      "label": "sibyl-memory.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0125",
      "label": "sibyl-token.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0126",
      "label": "sibyllabs-chat.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0127",
      "label": "talos.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0128",
      "label": "PRODUCT03",
      "family": "systems",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0129",
      "label": "PRODUCT04",
      "family": "systems",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0130",
      "label": "website.json",
      "family": "systems",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0131",
      "label": "COMPANY01",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0132",
      "label": "COMPANY02",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0133",
      "label": "COMPANY03",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0134",
      "label": "COMPANY04",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0135",
      "label": "COMPANY05",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0136",
      "label": "COMPANY06",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0137",
      "label": "COMPANY07",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0138",
      "label": "COMPANY08",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0139",
      "label": "COMPANY09",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0140",
      "label": "COMPANY10",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0141",
      "label": "COMPANY11",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0142",
      "label": "COMPANY12",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0143",
      "label": "COMPANY13",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0144",
      "label": "COMPANY14",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0145",
      "label": "COMPANY15",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0146",
      "label": "COMPANY16",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0147",
      "label": "COMPANY17",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0148",
      "label": "COMPANY18",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0149",
      "label": "COMPANY19",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0150",
      "label": "COMPANY20",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0151",
      "label": "COMPANY21",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0152",
      "label": "COMPANY22",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0153",
      "label": "COMPANY23",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0154",
      "label": "COMPANY24",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0155",
      "label": "COMPANY25",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0156",
      "label": "COMPANY26",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0157",
      "label": "COMPANY27",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0158",
      "label": "COMPANY28",
      "family": "projects",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0159",
      "label": "sibyl_labs_llc.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0160",
      "label": "actors.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0161",
      "label": "beta-bug-watch.jsonl",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0162",
      "label": "email-forwards.jsonl",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0163",
      "label": "errors.jsonl",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0164",
      "label": "2026-02-to-03-11.jsonl",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0165",
      "label": "current.jsonl",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0166",
      "label": "lint.jsonl",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0167",
      "label": "pr-outreach.jsonl",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0168",
      "label": "revenue.jsonl",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0169",
      "label": "system-health.jsonl",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0170",
      "label": "venice-calls.jsonl",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0171",
      "label": "OPS04",
      "family": "memory",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0172",
      "label": "ping-cache.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0173",
      "label": "OPS05",
      "family": "memory",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0174",
      "label": "OPS06",
      "family": "memory",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0175",
      "label": "queue.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0176",
      "label": "RAW01",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0177",
      "label": "RAW02",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0178",
      "label": "RAW03",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0179",
      "label": "acp-daemon-promotion-plan.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0180",
      "label": "acp-offerings-catalog.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0181",
      "label": "acp-runbook.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0182",
      "label": "ai-base-watchlist-2026-04-25.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0183",
      "label": "bankr-reference.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0184",
      "label": "benchmarks.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0185",
      "label": "blockchain-opsec.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0186",
      "label": "claim-portal-access.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0187",
      "label": "defi-exploits.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0188",
      "label": "defi-mastery.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0189",
      "label": "OPS07",
      "family": "memory",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0190",
      "label": "evaluation-framework.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0191",
      "label": "git-history-purge.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0192",
      "label": "google-oauth-reconnect.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0193",
      "label": "internal-email-section-modules.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0194",
      "label": "internal-email-template-creme-paper.html",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0195",
      "label": "operational-guidelines.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0196",
      "label": "operational-rules.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0197",
      "label": "outreach-blurb.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0198",
      "label": "partner-comms.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0199",
      "label": "partner-tiering-research.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0200",
      "label": "ping-video-guide.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0201",
      "label": "product-post-template.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0202",
      "label": "repo-governance.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0203",
      "label": "security-strategy.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0204",
      "label": "seo-tasks.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0205",
      "label": "sibyl-swarm-plan-v1.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0206",
      "label": "sibylcap-seo-audit-2026-04-19.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0207",
      "label": "skills.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0208",
      "label": "solidity-mastery.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0209",
      "label": "solution-files.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0210",
      "label": "staker-access-architecture.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0211",
      "label": "startup-procedure.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0212",
      "label": "swarm-plan-email-draft.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0213",
      "label": "team-comms.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0214",
      "label": "transactions.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0215",
      "label": "venice-inference-layer.txt",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0216",
      "label": "visual-identity.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0217",
      "label": "x402-expanded-catalog.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0218",
      "label": "x402-integrations.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0219",
      "label": "OPS08",
      "family": "memory",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0220",
      "label": "auth-wave1-step1-2026-05-19.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0221",
      "label": "OPS09",
      "family": "memory",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0222",
      "label": "reputation.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0223",
      "label": "RESEARCH01",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0224",
      "label": "RESEARCH02",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0225",
      "label": "RESEARCH03",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0226",
      "label": "RESEARCH04",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0227",
      "label": "RESEARCH05",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0228",
      "label": "RESEARCH06",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0229",
      "label": "RESEARCH07",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0230",
      "label": "RESEARCH08",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0231",
      "label": "RESEARCH09",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0232",
      "label": "RESEARCH10",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0233",
      "label": "RESEARCH11",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0234",
      "label": "RESEARCH12",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0235",
      "label": "RESEARCH13",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0236",
      "label": "RESEARCH14",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0237",
      "label": "RESEARCH15",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0238",
      "label": "RESEARCH16",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0239",
      "label": "RESEARCH17",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0240",
      "label": "RESEARCH18",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0241",
      "label": "RESEARCH19",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0242",
      "label": "RESEARCH20",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0243",
      "label": "RESEARCH21",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0244",
      "label": "RESEARCH22",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0245",
      "label": "RESEARCH23",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0246",
      "label": "RESEARCH24",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0247",
      "label": "RESEARCH25",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0248",
      "label": "RESEARCH26",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0249",
      "label": "RESEARCH27",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0250",
      "label": "RESEARCH28",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0251",
      "label": "RESEARCH29",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0252",
      "label": "RESEARCH30",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0253",
      "label": "RESEARCH31",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0254",
      "label": "RESEARCH32",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0255",
      "label": "RESEARCH33",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0256",
      "label": "RESEARCH34",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0257",
      "label": "RESEARCH35",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0258",
      "label": "RESEARCH36",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0259",
      "label": "RESEARCH37",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0260",
      "label": "RESEARCH38",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0261",
      "label": "RESEARCH39",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0262",
      "label": "RESEARCH40",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0263",
      "label": "RESEARCH41",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0264",
      "label": "RESEARCH42",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0265",
      "label": "RESEARCH43",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0266",
      "label": "RESEARCH44",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0267",
      "label": "scheduled-posts.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0268",
      "label": "scheduler.log",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0269",
      "label": "backlog.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0270",
      "label": "beta-watch.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0271",
      "label": "priorities-completed.jsonl",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0272",
      "label": "priorities-history.md",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0273",
      "label": "priorities.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0274",
      "label": "session.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0275",
      "label": "treasury.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0276",
      "label": "user-signal-cursors.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0277",
      "label": "SWARM01",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0278",
      "label": "SWARM02",
      "family": "workmem",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0279",
      "label": "live.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0280",
      "label": "paper.json",
      "family": "memory",
      "masked": false,
      "file": true,
      "degree": 1
    },
    {
      "id": "f0281",
      "label": "OPS10",
      "family": "memory",
      "masked": true,
      "file": true,
      "degree": 1
    },
    {
      "id": "h-people",
      "label": "entities/people ·18",
      "family": "people",
      "hub": true,
      "degree": 19
    },
    {
      "id": "h-projects",
      "label": "entities/projects ·28",
      "family": "projects",
      "hub": true,
      "degree": 31
    },
    {
      "id": "h-community",
      "label": "entities/community ·8",
      "family": "community",
      "hub": true,
      "degree": 11
    },
    {
      "id": "h-products",
      "label": "entities/products ·17",
      "family": "systems",
      "hub": true,
      "degree": 18
    },
    {
      "id": "h-state",
      "label": "state ·8",
      "family": "memory",
      "hub": true,
      "degree": 12
    },
    {
      "id": "h-logs",
      "label": "logs ·10",
      "family": "memory",
      "hub": true,
      "degree": 13
    },
    {
      "id": "h-reference",
      "label": "reference ·40",
      "family": "memory",
      "hub": true,
      "degree": 43
    },
    {
      "id": "h-archive",
      "label": "archive ·70",
      "family": "workmem",
      "hub": true,
      "degree": 71
    },
    {
      "id": "h-research",
      "label": "research ·44",
      "family": "workmem",
      "hub": true,
      "degree": 46
    },
    {
      "id": "h-endpoint",
      "label": "endpoint_reviews ·11",
      "family": "workmem",
      "hub": true,
      "degree": 12
    },
    {
      "id": "h-raw",
      "label": "raw ·3",
      "family": "workmem",
      "hub": true,
      "degree": 4
    },
    {
      "id": "h-swarm",
      "label": "swarm ·2",
      "family": "workmem",
      "hub": true,
      "degree": 3
    },
    {
      "id": "h-talos",
      "label": "talos ·2",
      "family": "memory",
      "hub": true,
      "degree": 4
    },
    {
      "id": "h-cache",
      "label": "cache ·1",
      "family": "memory",
      "hub": true,
      "degree": 2
    },
    {
      "id": "h-reports",
      "label": "reports ·1",
      "family": "memory",
      "hub": true,
      "degree": 2
    },
    {
      "id": "h-flagged",
      "label": "flagged ·1",
      "family": "memory",
      "hub": true,
      "degree": 2
    },
    {
      "id": "h-root",
      "label": "memory root ·17",
      "family": "memory",
      "hub": true,
      "degree": 18
    },
    {
      "id": "mcp-x",
      "label": "mcp: sibyl-x",
      "family": "senses",
      "degree": 2
    },
    {
      "id": "mcp-x402",
      "label": "mcp: sibyl-x402",
      "family": "senses",
      "degree": 3
    },
    {
      "id": "mcp-google",
      "label": "mcp: sibyl-google",
      "family": "senses",
      "degree": 3
    },
    {
      "id": "mcp-erc",
      "label": "mcp: sibyl-erc8004",
      "family": "senses",
      "degree": 1
    },
    {
      "id": "scr-trade",
      "label": "scripts: trading",
      "family": "senses",
      "aggregated": true,
      "degree": 2
    },
    {
      "id": "scr-ping",
      "label": "scripts: ping",
      "family": "senses",
      "aggregated": true,
      "degree": 1
    },
    {
      "id": "scr-research",
      "label": "scripts: research",
      "family": "senses",
      "aggregated": true,
      "degree": 1
    },
    {
      "id": "scr-comms",
      "label": "scripts: comms",
      "family": "senses",
      "aggregated": true,
      "degree": 1
    },
    {
      "id": "scr-wallet",
      "label": "scripts: wallet & security",
      "family": "senses",
      "aggregated": true,
      "degree": 1
    },
    {
      "id": "scr-guard",
      "label": "scripts: guardrails",
      "family": "senses",
      "aggregated": true,
      "degree": 1
    },
    {
      "id": "svc-talos",
      "label": "svc: talos-live",
      "family": "senses",
      "degree": 1
    },
    {
      "id": "svc-advisory",
      "label": "svc: advisory",
      "family": "senses",
      "degree": 2
    },
    {
      "id": "svc-discord",
      "label": "svc: discord",
      "family": "senses",
      "degree": 1
    },
    {
      "id": "sys-talos",
      "label": "Talos",
      "family": "systems",
      "color": "#e05252",
      "degree": 4
    },
    {
      "id": "sys-ping",
      "label": "Ping",
      "family": "systems",
      "color": "#34d399",
      "degree": 1
    },
    {
      "id": "sys-memory",
      "label": "Sibyl Memory",
      "family": "systems",
      "color": "#a78bfa",
      "degree": 3
    },
    {
      "id": "sys-framework",
      "label": "Framework Skill",
      "family": "systems",
      "degree": 1
    },
    {
      "id": "sys-advisory",
      "label": "Advisory Dashboard",
      "family": "systems",
      "degree": 2
    },
    {
      "id": "sys-website",
      "label": "Website",
      "family": "systems",
      "degree": 1
    },
    {
      "id": "sys-token",
      "label": "$SIBYL",
      "family": "systems",
      "color": "#d4b872",
      "degree": 3
    },
    {
      "id": "sys-auspex",
      "label": "AUSPEX",
      "family": "systems",
      "degree": 1
    },
    {
      "id": "sys-erc",
      "label": "ERC-8004 identity",
      "family": "systems",
      "degree": 2
    },
    {
      "id": "sys-chat",
      "label": "Sibyllabs Chat",
      "family": "systems",
      "degree": 1
    }
  ],
  "links": [
    {
      "source": "claude",
      "target": "p-spec",
      "kind": "reads"
    },
    {
      "source": "claude",
      "target": "p-voice",
      "kind": "reads"
    },
    {
      "source": "claude",
      "target": "p-soul",
      "kind": "reads"
    },
    {
      "source": "claude",
      "target": "p-talos",
      "kind": "reads"
    },
    {
      "source": "claude",
      "target": "p-erc",
      "kind": "reads"
    },
    {
      "source": "claude",
      "target": "p-sys",
      "kind": "reads"
    },
    {
      "source": "claude",
      "target": "p-gloss",
      "kind": "reads"
    },
    {
      "source": "claude",
      "target": "p-diary",
      "kind": "reads"
    },
    {
      "source": "claude",
      "target": "index",
      "kind": "reads"
    },
    {
      "source": "h-archive",
      "target": "f0001",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0002",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0003",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0004",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0005",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0006",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0007",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0008",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0009",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0010",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0011",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0012",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0013",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0014",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0015",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0016",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0017",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0018",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0019",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0020",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0021",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0022",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0023",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0024",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0025",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0026",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0027",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0028",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0029",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0030",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0031",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0032",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0033",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0034",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0035",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0036",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0037",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0038",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0039",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0040",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0041",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0042",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0043",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0044",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0045",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0046",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0047",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0048",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0049",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0050",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0051",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0052",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0053",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0054",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0055",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0056",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0057",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0058",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0059",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0060",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0061",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0062",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0063",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0064",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0065",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0066",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0067",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0068",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0069",
      "kind": "contains"
    },
    {
      "source": "h-archive",
      "target": "f0070",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0071",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0072",
      "kind": "contains"
    },
    {
      "source": "h-cache",
      "target": "f0073",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0074",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0075",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0076",
      "kind": "contains"
    },
    {
      "source": "h-endpoint",
      "target": "f0077",
      "kind": "contains"
    },
    {
      "source": "h-endpoint",
      "target": "f0078",
      "kind": "contains"
    },
    {
      "source": "h-endpoint",
      "target": "f0079",
      "kind": "contains"
    },
    {
      "source": "h-endpoint",
      "target": "f0080",
      "kind": "contains"
    },
    {
      "source": "h-endpoint",
      "target": "f0081",
      "kind": "contains"
    },
    {
      "source": "h-endpoint",
      "target": "f0082",
      "kind": "contains"
    },
    {
      "source": "h-endpoint",
      "target": "f0083",
      "kind": "contains"
    },
    {
      "source": "h-endpoint",
      "target": "f0084",
      "kind": "contains"
    },
    {
      "source": "h-endpoint",
      "target": "f0085",
      "kind": "contains"
    },
    {
      "source": "h-endpoint",
      "target": "f0086",
      "kind": "contains"
    },
    {
      "source": "h-endpoint",
      "target": "f0087",
      "kind": "contains"
    },
    {
      "source": "h-community",
      "target": "f0088",
      "kind": "contains"
    },
    {
      "source": "h-community",
      "target": "f0089",
      "kind": "contains"
    },
    {
      "source": "h-community",
      "target": "f0090",
      "kind": "contains"
    },
    {
      "source": "h-community",
      "target": "f0091",
      "kind": "contains"
    },
    {
      "source": "h-community",
      "target": "f0092",
      "kind": "contains"
    },
    {
      "source": "h-community",
      "target": "f0093",
      "kind": "contains"
    },
    {
      "source": "h-community",
      "target": "f0094",
      "kind": "contains"
    },
    {
      "source": "h-community",
      "target": "f0095",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0096",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0097",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0098",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0099",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0100",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0101",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0102",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0103",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0104",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0105",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0106",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0107",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0108",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0109",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0110",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0111",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0112",
      "kind": "contains"
    },
    {
      "source": "h-people",
      "target": "f0113",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0114",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0115",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0116",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0117",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0118",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0119",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0120",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0121",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0122",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0123",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0124",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0125",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0126",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0127",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0128",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0129",
      "kind": "contains"
    },
    {
      "source": "h-products",
      "target": "f0130",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0131",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0132",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0133",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0134",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0135",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0136",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0137",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0138",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0139",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0140",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0141",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0142",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0143",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0144",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0145",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0146",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0147",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0148",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0149",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0150",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0151",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0152",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0153",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0154",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0155",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0156",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0157",
      "kind": "contains"
    },
    {
      "source": "h-projects",
      "target": "f0158",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0159",
      "kind": "contains"
    },
    {
      "source": "h-flagged",
      "target": "f0160",
      "kind": "contains"
    },
    {
      "source": "h-logs",
      "target": "f0161",
      "kind": "contains"
    },
    {
      "source": "h-logs",
      "target": "f0162",
      "kind": "contains"
    },
    {
      "source": "h-logs",
      "target": "f0163",
      "kind": "contains"
    },
    {
      "source": "h-logs",
      "target": "f0164",
      "kind": "contains"
    },
    {
      "source": "h-logs",
      "target": "f0165",
      "kind": "contains"
    },
    {
      "source": "h-logs",
      "target": "f0166",
      "kind": "contains"
    },
    {
      "source": "h-logs",
      "target": "f0167",
      "kind": "contains"
    },
    {
      "source": "h-logs",
      "target": "f0168",
      "kind": "contains"
    },
    {
      "source": "h-logs",
      "target": "f0169",
      "kind": "contains"
    },
    {
      "source": "h-logs",
      "target": "f0170",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0171",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0172",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0173",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0174",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0175",
      "kind": "contains"
    },
    {
      "source": "h-raw",
      "target": "f0176",
      "kind": "contains"
    },
    {
      "source": "h-raw",
      "target": "f0177",
      "kind": "contains"
    },
    {
      "source": "h-raw",
      "target": "f0178",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0179",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0180",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0181",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0182",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0183",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0184",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0185",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0186",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0187",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0188",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0189",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0190",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0191",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0192",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0193",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0194",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0195",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0196",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0197",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0198",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0199",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0200",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0201",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0202",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0203",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0204",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0205",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0206",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0207",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0208",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0209",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0210",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0211",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0212",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0213",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0214",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0215",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0216",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0217",
      "kind": "contains"
    },
    {
      "source": "h-reference",
      "target": "f0218",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0219",
      "kind": "contains"
    },
    {
      "source": "h-reports",
      "target": "f0220",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0221",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0222",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0223",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0224",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0225",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0226",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0227",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0228",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0229",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0230",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0231",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0232",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0233",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0234",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0235",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0236",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0237",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0238",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0239",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0240",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0241",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0242",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0243",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0244",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0245",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0246",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0247",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0248",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0249",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0250",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0251",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0252",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0253",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0254",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0255",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0256",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0257",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0258",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0259",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0260",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0261",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0262",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0263",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0264",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0265",
      "kind": "contains"
    },
    {
      "source": "h-research",
      "target": "f0266",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0267",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0268",
      "kind": "contains"
    },
    {
      "source": "h-state",
      "target": "f0269",
      "kind": "contains"
    },
    {
      "source": "h-state",
      "target": "f0270",
      "kind": "contains"
    },
    {
      "source": "h-state",
      "target": "f0271",
      "kind": "contains"
    },
    {
      "source": "h-state",
      "target": "f0272",
      "kind": "contains"
    },
    {
      "source": "h-state",
      "target": "f0273",
      "kind": "contains"
    },
    {
      "source": "h-state",
      "target": "f0274",
      "kind": "contains"
    },
    {
      "source": "h-state",
      "target": "f0275",
      "kind": "contains"
    },
    {
      "source": "h-state",
      "target": "f0276",
      "kind": "contains"
    },
    {
      "source": "h-swarm",
      "target": "f0277",
      "kind": "contains"
    },
    {
      "source": "h-swarm",
      "target": "f0278",
      "kind": "contains"
    },
    {
      "source": "h-talos",
      "target": "f0279",
      "kind": "contains"
    },
    {
      "source": "h-talos",
      "target": "f0280",
      "kind": "contains"
    },
    {
      "source": "h-root",
      "target": "f0281",
      "kind": "contains"
    },
    {
      "source": "index",
      "target": "h-people",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-projects",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-community",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-products",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-state",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-logs",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-reference",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-archive",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-research",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-endpoint",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-raw",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-swarm",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-talos",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-cache",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-reports",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-flagged",
      "kind": "indexes"
    },
    {
      "source": "index",
      "target": "h-root",
      "kind": "indexes"
    },
    {
      "source": "claude",
      "target": "h-reference",
      "kind": "references"
    },
    {
      "source": "mcp-x402",
      "target": "sys-talos",
      "kind": "dataflow"
    },
    {
      "source": "mcp-x402",
      "target": "sys-token",
      "kind": "dataflow"
    },
    {
      "source": "mcp-x402",
      "target": "h-state",
      "kind": "reads"
    },
    {
      "source": "mcp-x",
      "target": "h-logs",
      "kind": "writes"
    },
    {
      "source": "mcp-x",
      "target": "p-voice",
      "kind": "reads"
    },
    {
      "source": "mcp-google",
      "target": "h-reference",
      "kind": "reads"
    },
    {
      "source": "mcp-google",
      "target": "h-logs",
      "kind": "writes"
    },
    {
      "source": "mcp-erc",
      "target": "sys-erc",
      "kind": "dataflow"
    },
    {
      "source": "scr-trade",
      "target": "sys-talos",
      "kind": "dataflow"
    },
    {
      "source": "scr-trade",
      "target": "h-talos",
      "kind": "writes"
    },
    {
      "source": "scr-ping",
      "target": "sys-ping",
      "kind": "dataflow"
    },
    {
      "source": "scr-research",
      "target": "h-research",
      "kind": "writes"
    },
    {
      "source": "scr-comms",
      "target": "mcp-google",
      "kind": "dataflow"
    },
    {
      "source": "scr-wallet",
      "target": "h-state",
      "kind": "dataflow"
    },
    {
      "source": "scr-guard",
      "target": "index",
      "kind": "dataflow"
    },
    {
      "source": "svc-talos",
      "target": "sys-talos",
      "kind": "dataflow"
    },
    {
      "source": "svc-advisory",
      "target": "sys-advisory",
      "kind": "dataflow"
    },
    {
      "source": "svc-advisory",
      "target": "h-projects",
      "kind": "dataflow"
    },
    {
      "source": "svc-discord",
      "target": "h-community",
      "kind": "dataflow"
    },
    {
      "source": "sys-memory",
      "target": "index",
      "kind": "dataflow"
    },
    {
      "source": "sys-framework",
      "target": "claude",
      "kind": "dataflow"
    },
    {
      "source": "sys-advisory",
      "target": "h-projects",
      "kind": "dataflow"
    },
    {
      "source": "sys-erc",
      "target": "claude",
      "kind": "dataflow"
    },
    {
      "source": "sys-token",
      "target": "h-community",
      "kind": "dataflow"
    },
    {
      "source": "sys-auspex",
      "target": "sys-token",
      "kind": "dataflow"
    },
    {
      "source": "sys-website",
      "target": "sys-memory",
      "kind": "dataflow"
    },
    {
      "source": "sys-chat",
      "target": "sys-memory",
      "kind": "dataflow"
    },
    {
      "source": "sys-talos",
      "target": "h-state",
      "kind": "dataflow"
    }
  ]
};
